[package]
name = "te-eval"
description = "Measures models for Text Explainer: speed, memory, readability gain, meaning and language faithfulness"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
te-core.workspace = true
te-win.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
